- .github/PULL_REQUEST_TEMPLATE.md
> create: PR template

- .github/PULL_REQUEST_TEMPLATE.md
- backend/server.js
Enviar arquivo do front na rota "/"
(opicional)
(opicional)
(opicional)
> create: get to send file

- frontend/index.js
Corrigir conexao WS estava quebrando
> fix: connection ws

- backend/src/routes/routes.js
- frontend/index.js
- frontend/style.css
- package-lock.json
- yarn.lock
desenvolvimento do chat do game 
(opicional)
(opicional)
(opicional)
> chat do game

- frontend/index.js
(opicional)
(opicional)
(opicional)
> fix: cursor

- frontend/src/scripts/home.js
- Reduzir o tamanho do script da página inicial.
- Não há rota configurada no back-end para esta página ser a inicial ao acessar o site/aplicação.
- No script da página inicial falta a rota para o envio da informação do nome/login para verificação dos jogadores existentes.
- Caso seja validado o nome, o jogador deverá ser redirecionado para a sala do jogo (ou criar uma). Aguardar direcionamento da equipe para definir o fluxo do jogo.
- Não está formatado para ter o layout dinâmico (está formatado somente para telas de desktop).
> improve: home page script

- .gitignore
- README.md
- frontend/home.html
- frontend/index.html
- frontend/index.js
- frontend/src/scripts/home.js
- package-lock.json
- package.json
- webpack.config.js
- yarn.lock
Qual a motivação desse PR?
Estou criando a configuração para o webpack, já é possível gerar o html e js, o css 
Observações / Pontos de atenção
Sempre que adicionar um novo .html lembre de adiciona-lo no webpack.config.js
Não é necessário importar nenhum tipo de js e css no html, importe o css no proprio js com esse comando: import css from /path/filename.css
Lembre-se de executar npm run build para gerar os arquivos .js, .css e .html
> Webpack migueç(sem bugs)

- backend/server.js
- frontend/index.html
- frontend/index.js
- package.json
- yarn.lock
> fix: webpack

- backend/src/routes/routes.js
- frontend/entry.js
- frontend/index.html
- frontend/index.js
- frontend/src/scripts/home.js
- webpack.config.js
Utilização do webpack
Todo arquivo `.js` deve estar dentro de um `try catch`
Lembre-se de importa-lo dentro do arquivo `entry.js`, pois senão ele não será adicionado no webpack
> Bug fixes miguel

- frontend/index.html
- frontend/index.js
- frontend/src/scripts/canvas.js
- frontend/src/scripts/home.js
- frontend/src/scripts/paint.js
- frontend/src/styles/home.css
- frontend/style.css
Mudar funções do código para class e modularizar.
> fix: change to class

- backend/src/index.js
- backend/src/routes/routes.js
Adicionar o controle de usuário pelo id e de canais.
**Não mergear o PR #22**
> feat: identify login

- frontend/src/scripts/home.js
- Organizar as mensagens de erro
- O idioma também foi padronizado nas seções alteradas
> improve: error messages of home.js

- frontend/index.js
Resolvendo um bug de entrar com os mesmos nomes de usuário.
> Solving login name problem

- backend/src/database/words.js
- frontend/src/scripts/guess.js
- Criar o banco de dados das palavras para serem sorteadas e a função para fazer verificação das mesmas através de tentativas.
- Este PR se trata literalmente da criação, e não implementação e funções adicionais eventualmente necessárias.
> create: words db and function for draw

- backend/src/database/words.js
- backend/src/routes/connection.js
- backend/src/routes/login.js
- frontend/index.js
- frontend/src/scripts/guess.js
- yarn.lock
Corrigir nomes duplicados
confia
> fix: duplicate name

- frontend/index.html
- frontend/index.js
- frontend/style.css
> Listing players

- backend/src/routes/connection.js
Enviar o id dos usuários para o front
> fix: send id user in array

- frontend/src/scripts/time.js
Criar a classe time
Não fiz nenhuma controle ou instancia dela
> feat: create time class

- backend/src/routes/chat.js
- backend/src/routes/connection.js
- backend/src/routes/draw.js
- backend/src/routes/login.js
ARRUMANDO MAAAAIS UMA VEEEZ O BUG DA LISTA
Eu coloquei um action no send, eu tava fazendo alguma coisa ontem e esqueci o que era e precisava disso, ent vou manter por hora
> fix: chatList send

- frontend/index.js
Atualizando a listagem de players ativos.
> Listando players ativos - atualização

- backend/server.js
- backend/src/routes/disconnection.js
- backend/src/routes/logout.js
- backend/src/routes/routes.js
- yarn.lock
Adicionar as classes que fazem a desconexão do usuário
(opicional)
(opicional)
(opicional)
> Created Logout and Disconnect classes

- backend/src/routes/login.js
- frontend/index.js
> fix list users

- backend/src/__mock__/data-mock.js
- backend/src/routes/connection.js
- backend/src/routes/game-control.js
- backend/src/routes/routes.js
- frontend/index.js
- frontend/src/utils/find-user.js
(opicional)
(opicional)
(opicional)
> Control drawing

- backend/app.js
- backend/src/database/index.js
- backend/src/index.js
- backend/src/routes/logout.js
- frontend/index.html
- frontend/index.js
- frontend/src/scripts/canvas.js
- frontend/src/scripts/home.js
Apagar cometários e consoles que não influenciam na aplicação e só geram mais texto que podem vir a atrapalhar a visualização e leitura.
- `console.log` que eram usados para visualizar erros sobre o servidor ou `try catch` foram substituídos por `console.error`
- Caso seja necessário ver alguma informação, posteriormente ao merge deste PR, colocar `console.log` somente durante o desenvolvimento local
- O `console.log` do `listen server` foi mantido
- Abrir o console do browser durante a execução da aplicação.
> refactor: delete unnecessary code and comments
